# Generated by Django 4.0.6 on 2022-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notes_options_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
