# Generated by Django 4.0.5 on 2022-07-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_notes_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='profile_pic',
        ),
    ]
