# Generated by Django 4.0.5 on 2022-07-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='yr_review',
        ),
    ]
