# Generated by Django 4.0.5 on 2022-07-24 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_reviews_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user',
            new_name='user_name',
        ),
    ]
