# Generated by Django 4.0.5 on 2022-07-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_rename_user_reviews_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user_name',
        ),
    ]
