# Generated by Django 4.0.5 on 2022-08-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_homework_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='due',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='subject',
        ),
    ]
